version: '3.9'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: flask run --host=0.0.0.0
    environment:
      - PORT=${BACKEND_PORT:-5000}
      - FLASK_RUN_PORT=${BACKEND_PORT:-5000}
      - FLASK_APP=${FLASK_APP:-app}
      - FLASK_ENV=${FLASK_ENV:-development}
      - FIRESTORE_PROJECT_ID=${FIRESTORE_PROJECT_ID:-demo-project}
      - FIRESTORE_EMULATOR_HOST=${FIRESTORE_EMULATOR_HOST:-firestore-emulator:8080}
      - SECRET_KEY=${SECRET_KEY:-dev-secret-key}
    ports:
      - '${BACKEND_PORT:-5000}:${BACKEND_PORT:-5000}'
    depends_on:
      - firestore-emulator
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: npm run dev -- --host --port ${FRONTEND_PORT:-5173}
    ports:
      - '${FRONTEND_PORT:-5173}:${FRONTEND_PORT:-5173}'
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL:-http://localhost:${BACKEND_PORT:-5000}}
    depends_on:
      - backend
  firestore-emulator:
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:emulators
    command: gcloud beta emulators firestore start --host-port=0.0.0.0:${FIRESTORE_EMULATOR_PORT:-8080} --project=${FIRESTORE_PROJECT_ID:-demo-project}
    ports:
      - '${FIRESTORE_EMULATOR_PORT:-8080}:${FIRESTORE_EMULATOR_PORT:-8080}'
    volumes:
      - firestore_data:/workspace
volumes:
  firestore_data:
