services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: flask run --host=0.0.0.0
    volumes:
      - ./backend:/app
    environment:
      - PORT=${BACKEND_PORT:-5000}
      - FLASK_RUN_PORT=${BACKEND_PORT:-5000}
      - FLASK_APP=${FLASK_APP:-app}
      - FLASK_ENV=${FLASK_ENV:-development}
      - DATA_BACKEND=${DATA_BACKEND:-tinydb}
      - TINYDB_FILE=${TINYDB_FILE:-/app/var/tinydb.json}
      - SECRET_KEY=${SECRET_KEY:-dev-secret-key}
    ports:
      - '${BACKEND_PORT:-5000}:${BACKEND_PORT:-5000}'
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: npm run dev -- --host --port ${FRONTEND_PORT:-5173}
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - '${FRONTEND_PORT:-5173}:${FRONTEND_PORT:-5173}'
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL:-http://localhost:${BACKEND_PORT:-5000}}
    depends_on:
      - backend
volumes:
  frontend_node_modules:
